"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from urllib.parse import urlparse
from django.conf import settings

# import django_heroku
import environ
from django.core.exceptions import ImproperlyConfigured
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/
env = environ.Env()
env.read_env(os.path.join(BASE_DIR, '.env'))

DEBUG = env.bool('DEBUG', default=True)

def get_backend_url():
    try:
        if DEBUG == True:
            return config("DEVELOPMENT_URL")
        else:
            return config("PRODUCTION_URL")
    except KeyError as e:
        env_var = "DEVELOPMENT_URL" if DEBUG else "PRODUCTION_URL"
        error_msg = f"set the {env_var} environment variable"
        raise ImproperlyConfigured(error_msg)

def get_frontend_url():
    try:
        if DEBUG == True:
            return config("FRONT_END_URL_DEV")
        else:
            return config("FRONT_END_URL_PROD")
    except KeyError as e:
        env_var = "FRONT_END_URL_DEV" if DEBUG else "FRONT_END_URL_PROD"
        error_msg = f"set the {env_var} environment variable"
        raise ImproperlyConfigured(error_msg)

def get_hunter_api_key():
    return config("HUNTER_IO_KEY", default="")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-dev-key-change-in-production')

#CHAPA
CHAPA_SECRET_KEY = env('CHAPA_SECRET_KEY', default='')
CHAPA_CALLBACK_URL = env('CHAPA_CALLBACK_URL', default='')

# SECURITY WARNING: don't run with debug turned on in production!


# ALLOWED_HOSTS - Restrict to specific school domains to prevent abuse
# Can be set via environment variable ALLOWED_HOSTS (comma-separated)
ALLOWED_HOSTS_ENV = env('ALLOWED_HOSTS', default='')
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(',') if host.strip()]
else:
    # Default allowed hosts for school domains
    ALLOWED_HOSTS = [
        "takethestage-api.onrender.com",
        "takethestageplc.com",
        "takethestage.org",
        "localhost",
        "127.0.0.1",
    ]
    # Add production backend URL if available
    try:
        backend_url = get_backend_url()
        if backend_url:
            parsed = urlparse(backend_url)
            if parsed.netloc and parsed.netloc not in ALLOWED_HOSTS:
                ALLOWED_HOSTS.append(parsed.netloc)
    except Exception:
        pass 

API_GENERATOR = {
    # 'students'  : "accounts.models.Student",
    # 'teachers'  : "accounts.models.Teacher",
    # 'attendances': "assessment.models.Attendance",
    # 'results': "assessment.models.Result",
    # 'teacher-shifts': "assessment.models.TeacherShift",
    # 'applications': "assessment.models.Application",
    # 'news': 'engagement.models.News',
    # 'payments': 'finance.models.Payment',
    # 'regions': 'organization.models.Region',
    # 'cities': 'organization.models.City',
    # 'institutions': 'organization.models.Institution',
    # 'class_rooms': 'organization.models.ClassRoom',
    # 'teacher-class-shifts': 'accounts.models.TeacherClassShift',
    # 'levels': 'lookup.models.Level',
    # 'packages': 'lookup.models.Package',
    # 'class-types': 'lookup.models.ClassType',
    # 'shfts': 'lookup.models.Shift',
    # 'class-room-shifts': 'organization.models.ClassRoomShift',
    # 'payment-webhook-events': 'finance.models.PaymentWebhookEvent'
    # 'teacher-request-shifts': 'accounts.models.TeacherRequestShift'
    # 'student-request-shifts': 'accounts.models.StudentRequestShift'
    # 'contact_us': 'commons.feedback.models.ContactUs',
    'student-class-shifts': 'accounts.models.StudentClassShift',
}

WEB_GENERATOR_PATH = env('WEB_GENERATOR_PATH', default='')

# Application definition

INSTALLED_APPS = [
    'django_chapa',
    'django_api_gen',
    # 'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    # 3rd-party apps
    'corsheaders',
    'whitenoise.runserver_nostatic',

    'rest_framework.authtoken',
    'rest_framework',
    'dj_rest_auth',
    'dj_rest_auth.registration',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    "django_filters",
    'rest_framework_simplejwt.token_blacklist',
    # "drf_spectacular",
    'notifications',
    'django_crontab',
    # Local

    # Common apps
    'commons.apps.CommonsConfig',
    'commons.authentication.apps.AuthenticationConfig',
    'commons.message_util.apps.MessageUtilConfig',
    'commons.feedback.apps.FeedbackConfig',
    'commons.about_us.apps.AboutUsConfig',
    'commons.text_chat.apps.TextChatConfig',
    'commons.notification.apps.NotificationConfig',
    'commons.file.apps.FileConfig',
    'commons.multi_languages.apps.MultiLanguagesConfig',
    'medias.apps.MediaConfig',
    # Apps
    'accounts.apps.AccountsConfig',
    'assessment.apps.AssessmentConfig',
    'engagement.apps.EngagementConfig',
    'finance.apps.FinanceConfig',
    'organization.apps.OrganizationConfig',
    'lookup.apps.LookupConfig',

    # Global Search
    'watson'
]

# CHAPA
CHAPA_SECRET = env('CHAPA_SECRET', default='')
CHAPA_API_URL = env('CHAPA_API_URL', default='https://api.chapa.co/v1')
CHAPA_WEBHOOK_SECRET = env('CHAPA_WEBHOOK_SECRET', default='')

CHAPA_API_VERSION = 'v1'

CHAPA_TRANSACTION_MODEL = 'django_chapa.ChapaTransaction'



# OAuth credentials - loaded from environment variables
GOOGLE_CLIENT_ID = env('GOOGLE_CLIENT_ID', default='')
GOOGLE_CLIENT_SECRET = env('GOOGLE_CLIENT_SECRET', default='')
GITHUB_CLIENT_ID = env('GITHUB_CLIENT_ID', default='')
GITHUB_CLIENT_SECRET = env('GITHUB_CLIENT_SECRET', default='')
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = env('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY', default='')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = env('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET', default='')

SITE_ID = 1
LOGIN_REDIRECT_URL = "socialaccount_signup"
ACCOUNT_LOGOUT_ON_GET = True

CRONJOBS = [
    ('53 12 * * *', 'finance.views.generatePayment', '>> your_log_file.log'),
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': 'django_errors.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        'APP': {
            'client_id': GOOGLE_CLIENT_ID,
            'secret': GOOGLE_CLIENT_SECRET,
            'key': ''
        }
    },'github': {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        'APP': {
            'client_id': GITHUB_CLIENT_ID,
            'secret': GITHUB_CLIENT_SECRET,
            'key': ''
        }
    }
}

TELEGRAM_BOT_TOKEN = env('TELEGRAM_BOT_TOKEN', default='')
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_EMAIL_REQUIRED = False
SOCIALACCOUNT_QUERY_EMAIL = True

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
        'commons.authentication.thread_local_jwt.ThreadLocalJWTAuthentication',
    ),

    # "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "commons.utils.exceptions.api_exception_handler",
    'DEFAULT_PAGINATION_CLASS': 'commons.utils.paginations.CustomPagination',
    'PAGE_SIZE': 100,
    
    # API Throttling - Rate limiting to prevent abuse
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',  # For unauthenticated users
        'rest_framework.throttling.UserRateThrottle',  # For authenticated users
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',  # 100 requests per hour for anonymous users
        'user': '1000/hour',  # 1000 requests per hour for authenticated users
    },
}

MIDDLEWARE = [
    # "kolo.middleware.KoloMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'watson.middleware.SearchContextMiddleware',
]

ROOT_URLCONF = 'take_the_stage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# CORS configuration - Restrict to specific school domains to prevent abuse
# Can be set via environment variable CORS_ALLOWED_ORIGINS (comma-separated)
CORS_ALLOWED_ORIGINS_ENV = env('CORS_ALLOWED_ORIGINS', default='')
if CORS_ALLOWED_ORIGINS_ENV:
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in CORS_ALLOWED_ORIGINS_ENV.split(',') if origin.strip()]
else:
    # Default CORS allowed origins for school domains
    CORS_ALLOWED_ORIGINS = [
        "https://takethestage-web.onrender.com",
        "https://takethestageplc.com",
        "https://takethestage.org",
        "http://localhost:3000",
        "http://localhost:3001",
        "http://127.0.0.1:3000",
        "http://127.0.0.1:3001",
    ]
    # Add production frontend URL if available
    try:
        frontend_url = get_frontend_url()
        if frontend_url:
            parsed = urlparse(frontend_url)
            if parsed.netloc:
                origin = f"{parsed.scheme}://{parsed.netloc}"
                if origin not in CORS_ALLOWED_ORIGINS:
                    CORS_ALLOWED_ORIGINS.append(origin)
    except Exception:
        pass

# Disable wildcard CORS
CORS_ALLOW_ALL_ORIGINS = False

# CSRF trusted origins - Must match CORS origins for forms to work
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS.copy()

# dependencies = [
#     # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
# ]

WSGI_APPLICATION = 'take_the_stage.wsgi.application'
# ASGI_APPLICATION = 'take_the_stage.asgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        "PASSWORD": env('DB_PASSWORD'),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,  # Enforce minimum password length
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'take_the_stage.validator.AlphaNumericPasswordValidator',
    },
]

# Password Hashing - Use Argon2 for better security (requires argon2-cffi package)
# Falls back to PBKDF2 if Argon2 is not available
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',  # Most secure, requires argon2-cffi
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',  # Default, very secure
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

REST_USE_JWT = True
# JWT_AUTH_COOKIE = 'my-app-auth'
# JWT_AUTH_REFRESH_COOKIE = 'my-refresh-token'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'django-api/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]  # new
STATIC_ROOT = BASE_DIR / "staticfiles"  # new

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

PASSWORD_RESET_TIMEOUT = 604800

# ============================================================================
# SECURITY SETTINGS - Production Security Configuration
# ============================================================================

# SSL/HTTPS Security
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# Only enable HTTPS redirect in production (when DEBUG=False)
if not DEBUG:
    SECURE_SSL_REDIRECT = True  # Redirect all HTTP requests to HTTPS
    SECURE_HSTS_SECONDS = 31536000  # 1 year - HTTP Strict Transport Security
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Include subdomains in HSTS
    SECURE_HSTS_PRELOAD = True  # Enable HSTS preload for browsers
else:
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0

# Cookie Security
SESSION_COOKIE_SECURE = not DEBUG  # Only send session cookies over HTTPS in production
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookies
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection for session cookies

CSRF_COOKIE_SECURE = not DEBUG  # Only send CSRF cookies over HTTPS in production
CSRF_COOKIE_HTTPONLY = True  # Prevent JavaScript access to CSRF cookies
CSRF_COOKIE_SAMESITE = 'Lax'  # CSRF protection

# Security Headers
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking attacks (prevent iframe embedding)
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing
SECURE_BROWSER_XSS_FILTER = True  # Enable browser XSS filter
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'  # Control referrer information

# Additional Security Headers (via middleware)
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'  # Prevent cross-origin attacks

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
# new
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field
LOGIN_URL = "commons/authorize/login"
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_CONFIRM_EMAIL_ON_GET = True

# Frontend URLs - loaded from environment variables
FRONTEND_BASE_URL = env('FRONTEND_BASE_URL', default='')
if not FRONTEND_BASE_URL:
    try:
        FRONTEND_BASE_URL = get_frontend_url() if not DEBUG else 'http://localhost:3000'
    except:
        FRONTEND_BASE_URL = 'http://localhost:3000'

ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = env('ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL', default=f'{FRONTEND_BASE_URL}/user/activate/12')
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = env('ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL', default=None)
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3

# Brevo configuration
BREVO_API_KEY = env("BREVO_API_KEY", default='')


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', default='')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', default=False)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
EMAIL_FAIL_SILENTLY = False

DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='takethestage@gmail.com')

ACCOUNT_EMAIL_REQUIRED = False

AUTH_USER_MODEL = 'authentication.CustomUser'

SPECTACULAR_SETTINGS = {
    "TITLE": "eTutor API Project",
    "DESCRIPTION": "eTutor platform build for geezTech",
    "VERSION": "1.0.0",
    # OTHER SETTINGS
}

RESET_PASSWORD_VERIFICATION_URL = env('RESET_PASSWORD_VERIFICATION_URL', default=f'{FRONTEND_BASE_URL}/reset_pwd')
URL_FRONT = env('URL_FRONT', default=f'{FRONTEND_BASE_URL}/')
ACCOUNT_ADAPTER = 'commons.utils.authenticaton_utils.DefaultAccountAdapterCustom'
REGISTER_VERIFICATION_URL = env('REGISTER_VERIFICATION_URL', default=f'{FRONTEND_BASE_URL}/user/activate')


REST_AUTH_SERIALIZERS = {
    'USER_DETAILS_SERIALIZER': 'commons.authentication.serializer.UserSerializer',
}

BREVO_SENDER = {
    'EMAIL': env('BREVO_SENDER_EMAIL', default=DEFAULT_FROM_EMAIL),
    'NAME': env('BREVO_SENDER_NAME', default="Take The Stage")
}

AuthenticationBackend = [
    'django.contrib.auth.backends.ModelBackend',
    'social_core.backends.google.GoogleOAuth2',
    'allauth.account.auth_backends.AuthenticationBackend',
]



# Managing refresh tokens
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=50),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=3),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    # "SIGNING_KEY": settings.SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=0.5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(minutes=2),
    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}
# django_heroku.settings(locals())

# Channels / Redis configuration
REDIS_HOST = env('REDIS_HOST', default='127.0.0.1')
REDIS_PORT = env.int('REDIS_PORT', default=6379)
REDIS_PASSWORD = env('REDIS_PASSWORD', default=None)

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, REDIS_PORT)],
            "password": REDIS_PASSWORD if REDIS_PASSWORD else None,
        },
    },
}

# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels.layers.InMemoryChannelLayer"
#     }
# }
# if os.environ.get('NOTIFY', False):
#     # INSTALLED_APPS.remove('notifications')
#     # INSTALLED_APPS.append('commons.notification')

# NOTIFICATIONS_NOTIFICATION_MODEL = 'commons.notification.models.Notification'


# File Upload Security
DATA_UPLOAD_MAX_MEMORY_SIZE = 12621440  # ~12 MB max file size in memory
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000  # Limit number of form fields to prevent DoS
FILE_UPLOAD_MAX_MEMORY_SIZE = 12621440  # Max file size before writing to disk
FILE_UPLOAD_PERMISSIONS = 0o644  # File permissions for uploaded files
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755  # Directory permissions for upload directories

# Production Security Warnings
if DEBUG:
    import warnings
    warnings.filterwarnings(
        'error',
        category=RuntimeWarning,
        module='django.*',
    )

# Prevent accidental exposure of sensitive data in error messages
if not DEBUG:
    # Don't expose sensitive information in error pages
    ADMINS = [('Admin', env('ADMIN_EMAIL', default='admin@takethestageplc.com'))]
    MANAGERS = ADMINS 