"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from django.conf import settings

# import django_heroku
import environ
from django.core.exceptions import ImproperlyConfigured
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/
environ.Env.read_env()
env = environ.Env()

DEBUG = env.bool('DEBUG', default=True)

def get_backend_url():
    try:
        if DEBUG == True:
            return config("DEVELOPMENT_URL")
        else:
            return config("PRODUCTION_URL")
    except KeyError:
        error_msg = "set the %s environment variable" 
        raise ImproperlyConfigured(error_msg)

def get_frontend_url():
    try:
        if DEBUG == True:
            return config("FRONT_END_URL_DEV")
        else:
            return config("FRONT_END_URL_PROD")
    except KeyError:
        error_msg="environment variable error"
        raise ImproperlyConfigured(error_msg)

def get_hunter_api_key():
    return config("HUNTER_IO_KEY")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

#CHAPA
CHAPA_SECRET_KEY = env('CHAPA_SECRET_KEY')
CHAPA_CALLBACK_URL = env('CHAPA_CALLBACK_URL')

# SECURITY WARNING: don't run with debug turned on in production!


# ALLOWED_HOSTS = [".herokuapp.com", "localhost", "127.0.0.1"]
ALLOWED_HOSTS = ["*"] 

API_GENERATOR = {
    # 'students'  : "accounts.models.Student",
    # 'teachers'  : "accounts.models.Teacher",
    # 'attendances': "assessment.models.Attendance",
    # 'results': "assessment.models.Result",
    # 'teacher-shifts': "assessment.models.TeacherShift",
    # 'applications': "assessment.models.Application",
    # 'news': 'engagement.models.News',
    # 'payments': 'finance.models.Payment',
    # 'regions': 'organization.models.Region',
    # 'cities': 'organization.models.City',
    # 'institutions': 'organization.models.Institution',
    # 'class_rooms': 'organization.models.ClassRoom',
    # 'teacher-class-shifts': 'accounts.models.TeacherClassShift',
    # 'levels': 'lookup.models.Level',
    # 'packages': 'lookup.models.Package',
    # 'class-types': 'lookup.models.ClassType',
    # 'shfts': 'lookup.models.Shift',
    # 'class-room-shifts': 'organization.models.ClassRoomShift',
    # 'payment-webhook-events': 'finance.models.PaymentWebhookEvent'
    # 'teacher-request-shifts': 'accounts.models.TeacherRequestShift'
    # 'student-request-shifts': 'accounts.models.StudentRequestShift'
    # 'contact_us': 'commons.feedback.models.ContactUs',
    'student-class-shifts': 'accounts.models.StudentClassShift',
}

WEB_GENERATOR_PATH = env('WEB_GENERATOR_PATH')

# Application definition

INSTALLED_APPS = [
    'django_chapa',
    'django_api_gen',
    # 'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    # 3rd-party apps
    'corsheaders',
    'whitenoise.runserver_nostatic',

    'rest_framework.authtoken',
    'rest_framework',
    'dj_rest_auth',
    'dj_rest_auth.registration',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    "django_filters",
    'rest_framework_simplejwt.token_blacklist',
    # "drf_spectacular",
    'notifications',
    'django_crontab',
    # Local

    # Common apps
    'commons.apps.CommonsConfig',
    'commons.authentication.apps.AuthenticationConfig',
    'commons.message_util.apps.MessageUtilConfig',
    'commons.feedback.apps.FeedbackConfig',
    'commons.about_us.apps.AboutUsConfig',
    'commons.text_chat.apps.TextChatConfig',
    'commons.notification.apps.NotificationConfig',
    'commons.file.apps.FileConfig',
    'commons.multi_languages.apps.MultiLanguagesConfig',
    'medias.apps.MediaConfig',
    # Apps
    'accounts.apps.AccountsConfig',
    'assessment.apps.AssessmentConfig',
    'engagement.apps.EngagementConfig',
    'finance.apps.FinanceConfig',
    'organization.apps.OrganizationConfig',
    'lookup.apps.LookupConfig',

    # Global Search
    'watson'
]

# CHAPA
CHAPA_SECRET = env('CHAPA_SECRET')

CHAPA_API_URL = env('CHAPA_API_URL')

CHAPA_API_VERSION = 'v1'

CHAPA_TRANSACTION_MODEL = 'django_chapa.ChapaTransaction'



# Put these in the .env file
GOOGLE_CLIENT_ID = "1083581779556-8aqk49a2490ramsc3ucghh6spe9murej.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
GITHUB_CLIENT_ID = "07a8752bcbc4ac250cc9"
GITHUB_CLIENT_SECRET = "5bf6ea3c989a2c4e38c480bcf32cf910f45e9865"
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '1026823299290-hvidfs6hva19v4135em3f7kbb3r3db7v.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'

SITE_ID = 1
LOGIN_REDIRECT_URL = "socialaccount_signup"
ACCOUNT_LOGOUT_ON_GET = True

CRONJOBS = [
    ('53 12 * * *', 'finance.views.generatePayment', '>> your_log_file.log'),
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': 'django_errors.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        'APP': {
            'client_id': '1083581779556-8aqk49a2490ramsc3ucghh6spe9murej.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
        }
    },'github': {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        'APP': {
            'client_id': '07a8752bcbc4ac250cc9',
            'secret': '5bf6ea3c989a2c4e38c480bcf32cf910f45e9865',
            'key': ''
        }
    }
}

TELEGRAM_BOT_TOKEN="6667695976:AAFPg0dsl2yF3D51q4tJ7QJcc8Lh_w60an0"
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_EMAIL_REQUIRED = False
SOCIALACCOUNT_QUERY_EMAIL = True

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
        'commons.authentication.thread_local_jwt.ThreadLocalJWTAuthentication',
    ),

    # "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "commons.utils.exceptions.api_exception_handler",
    'DEFAULT_PAGINATION_CLASS': 'commons.utils.paginations.CustomPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
}

MIDDLEWARE = [
    # "kolo.middleware.KoloMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'watson.middleware.SearchContextMiddleware',
]

ROOT_URLCONF = 'take_the_stage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# CORS_ALLOWED_ORIGINS = (
#     "http://localhost:3000",
#     "http://localhost:3001",
#     "http://localhost:8000",
# )
CORS_ALLOW_ALL_ORIGINS = True
# CSRF_TRUSTED_ORIGINS = ["http://localhost:3000"]
# CSRF_TRUSTED_ORIGINS = ["*"]

# dependencies = [
#     # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
# ]

WSGI_APPLICATION = 'take_the_stage.wsgi.application'
# ASGI_APPLICATION = 'take_the_stage.asgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        "PASSWORD": env('DB_PASSWORD'),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    
    {
        'NAME': 'take_the_stage.validator.AlphaNumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

REST_USE_JWT = True
# JWT_AUTH_COOKIE = 'my-app-auth'
# JWT_AUTH_REFRESH_COOKIE = 'my-refresh-token'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'django-api/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]  # new
STATIC_ROOT = BASE_DIR / "staticfiles"  # new

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

PASSWORD_RESET_TIMEOUT = 604800

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
# new
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field
LOGIN_URL = "commons/authorize/login"
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = "http://localhost:3000/user/activate/12"
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = None
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3

# Brevo configuration
BREVO_API_KEY = env("BREVO_API_KEY")


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = "mail.takethestageplc.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = "admin@takethestageplc.com"
EMAIL_HOST_PASSWORD = "Q?lvpf.I(m5-Q9)e"
EMAIL_FAIL_SILENTLY = False

DEFAULT_FROM_EMAIL = 'takethestage@gmail.com'

ACCOUNT_EMAIL_REQUIRED = False

AUTH_USER_MODEL = 'authentication.CustomUser'

SPECTACULAR_SETTINGS = {
    "TITLE": "eTutor API Project",
    "DESCRIPTION": "eTutor platform build for geezTech",
    "VERSION": "1.0.0",
    # OTHER SETTINGS
}
DEFAULT_FROM_EMAIL = 'contact@nisirtech.com'
RESET_PASSWORD_VERIFICATION_URL = "http://127.0.0.1:3000/reset_pwd"
URL_FRONT = "http://127.0.0.1:3000/"
ACCOUNT_ADAPTER = 'commons.utils.authenticaton_utils.DefaultAccountAdapterCustom'
REGISTER_VERIFICATION_URL = "http://localhost:3000/user/activate"


REST_AUTH_SERIALIZERS = {
    'USER_DETAILS_SERIALIZER': 'commons.authentication.serializer.UserSerializer',
}

BREVO_SENDER = {
    'EMAIL': 'takethestage@gmail.com',
    'NAME': "Take The Stage"
}

AuthenticationBackend = [
    'django.contrib.auth.backends.ModelBackend',
    'social_core.backends.google.GoogleOAuth2',
    'allauth.account.auth_backends.AuthenticationBackend',
]



# Managing refresh tokens
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=50),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=3),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    # "SIGNING_KEY": settings.SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=0.5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(minutes=2),
    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}
# django_heroku.settings(locals())

# Channels
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels.layers.InMemoryChannelLayer"
#     }
# }
# if os.environ.get('NOTIFY', False):
#     # INSTALLED_APPS.remove('notifications')
#     # INSTALLED_APPS.append('commons.notification')

# NOTIFICATIONS_NOTIFICATION_MODEL = 'commons.notification.models.Notification'


DATA_UPLOAD_MAX_MEMORY_SIZE = 12621440 